name: nail_detection
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pillow
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - ultralytics
    - opencv-python
    - seaborn
    - pyyaml